### ISSUE TITLE
版本检测疑似有误

### ISSUE THREAD

**Issue by DogeTwo** [BlackCleaverLoli/MissFisher#1]
我使用了1.2.0.4版本的trn，不过触发器虽然能正常使用但是每次按下任何交互都会提示版本过低，trn版本需要高于1.2.0.115，可我这是1.2.0.4啊喂

**Comment by BlackCleaverLoli** [comment]
版本检测确实有问题。因我开发使用的trn是一个 fork 版本，为了防止被 act 自动更新，这个 fork 的版本号中迭代版本会使用 3 位数，而主库使用的是 1 位数。
等我检查完另外一个问题后将立刻修复版本检测。

**Comment by BlackCleaverLoli** [comment]
你可以在分组：“主分组”-“一个空名分组”-“非限定”-“检查环境”中找到触发器“检查配置”，将其移除可以临时解决问题。
