### ISSUE TITLE
似乎无法正确序列化

### ISSUE THREAD

**Issue by lileii** [BlackCleaverLoli/MissFisher#2]
![1722065534083](https://github.com/user-attachments/assets/65c947d1-980d-4db0-ab13-15d800813288)

win11 
ACT.呆萌整合

**Comment by BlackCleaverLoli** [comment]
你好，请确认你的 Triggernometry 版本在 1.2.0.4 或 1.2.0.115（[MnFeN‘s Triggernometry](https://github.com/MnFeN/)） 以上，建议使用 [MnFeN‘s Triggernometry](https://github.com/MnFeN/)。

**Comment by lileii** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lileii** [comment]
ACT.呆萌整合 版本似乎比较低，重新用了Triggernometry新版本 v1.2.0.7 似乎有了新的错误
![bug1](https://github.com/user-attachments/assets/7390fd36-a969-4b34-b20f-6624fe5bd5fb)

**Comment by BlackCleaverLoli** [comment]
> ACT.呆萌整合 版本似乎比较低，重新用了Triggernometry新版本 v1.2.0.7 似乎有了新的错误 ![bug1](https://private-user-images.githubusercontent.com/66057369/352708853-7390fd36-a969-4b34-b20f-6624fe5bd5fb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjc0MzQsIm5iZiI6MTcyMjA2NzEzNCwicGF0aCI6Ii82NjA1NzM2OS8zNTI3MDg4NTMtNzM5MGZkMzYtYTk2OS00YjM0LWIyMGYtNjYyNGZlNWJkNWZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA3NTg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYTkzOWIzMjI0MzIwMzJiODZjM2ZjYTA4ZDE5NTM2NzRjMmZiMzIwNTg3MDg3NWY4NjhmYWI5ZjEwN2FmOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.51Uzu04Ie0RHw_0tk6b3iBm8fVx7-SqN25vUTaIorcM)

请确认远程触发器的仓库地址为 `https://github.com/BlackCleaverLoli/MissFisher/blob/main/MissFisher.xml` 或 `https://github.com/BlackCleaverLoli/MissFisher/blob/main/MissFisher%20Snapshot.xml`

**Comment by lileii** [comment]
![bug2](https://github.com/user-attachments/assets/93f6165f-78af-4ef9-a85b-a668f6c1b1ac)
两个xml文件都试过了，同时用的是最新的Triggernometry  依旧提示版本差异

**Comment by BlackCleaverLoli** [comment]
建议你尝试下载原文件，或复制文件内容，通过剪贴板或本地文件来导入

**Comment by lileii** [comment]
已通过本地导入xml的形势成功安装，谢谢BlackCleaverLoli，礼问这两个xml有什么区别

**Comment by lileii** [comment]
糟糕的是，本地导入似乎无法打开主界面
![Uploading 1722069154978.jpg…]()

**Comment by BlackCleaverLoli** [comment]
> 已通过本地导入xml的形势成功安装，谢谢BlackCleaverLoli，礼问这两个xml有什么区别

其中一个是 Snapshot 快照版，会经常更新，测试新功能。

**Comment by lileii** [comment]
糟糕的是，本地导入似乎无法打开主界面
![1722069154978](https://github.com/user-attachments/assets/def84309-fe85-48be-a3a7-f36c90923a5d)

**Comment by BlackCleaverLoli** [comment]
> 糟糕的是，本地导入似乎无法打开主界面 ![1722069154978](https://private-user-images.githubusercontent.com/66057369/352710588-def84309-fe85-48be-a3a7-f36c90923a5d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNjk4ODQsIm5iZiI6MTcyMjA2OTU4NCwicGF0aCI6Ii82NjA1NzM2OS8zNTI3MTA1ODgtZGVmODQzMDktZmU4NS00OGJlLWEzYTctZjM2YzkwOTIzYTVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA4Mzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZDRlM2Y3ZWVlMDkxOTQyMGUxNjFkYWM1NTBjYmE3NDkxYjllMGUzOWRmNTlmOGRiMTJmNDQxNDFmYjgwZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3XHzE60HfY4dWr8XOLruc5ftzp7cpU6HsuS7NrOgk_Y)

游戏是否已经打开？如果游戏没有在运行，窗口可能无法打开。

**Comment by MnFeN** [comment]
https://www.123pan.com/s/1xRXjv-340BH.html
装这个版本自检

**Comment by BlackCleaverLoli** [comment]
> 糟糕的是，本地导入似乎无法打开主界面 ![1722069154978](https://private-user-images.githubusercontent.com/66057369/352710588-def84309-fe85-48be-a3a7-f36c90923a5d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzA0NTAsIm5iZiI6MTcyMjA3MDE1MCwicGF0aCI6Ii82NjA1NzM2OS8zNTI3MTA1ODgtZGVmODQzMDktZmU4NS00OGJlLWEzYTctZjM2YzkwOTIzYTVkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDA4NDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZWI5OTEyOTlkNjQ2NDk2NWEzYzliNmMyMzkxMDc0ZmMyYzBiODU5NzllN2Y1NDFjYTEwYzIyMmEzMGE3ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l1tUtaWAAhWIg3UUYbIMl1LppTcrWDlJQvzpaWkWKjg)

请确认在安装新的 Trn 后有无重启 ACT。

**Comment by lileii** [comment]
这是我的版本
![1722070330121](https://github.com/user-attachments/assets/6f63fdae-6096-43df-95f1-244157d11746)

**Comment by BlackCleaverLoli** [comment]
请尝试在插件列表对插件进行排序：（1）FFXIV_ACT_Plugin（2）OverlayPlugin（3）Triggernometry（4）CactbotOverlay（5）PostNamazu（6）Cafe.Matcha（其他无关紧要的插件）
然后重启 ACT

**Comment by lileii** [comment]
感谢！ 【请尝试在插件列表对插件进行排序】是需要的
![1722071032483](https://github.com/user-attachments/assets/7486132c-7162-4140-92cf-844916ab572f)

**Comment by BlackCleaverLoli** [comment]
> ![1722065534083](https://private-user-images.githubusercontent.com/66057369/352707698-65c947d1-980d-4db0-ab13-15d800813288.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwOTgzMDEsIm5iZiI6MTcyMjA5ODAwMSwicGF0aCI6Ii82NjA1NzM2OS8zNTI3MDc2OTgtNjVjOTQ3ZDEtOTgwZC00ZGIwLWFiMTMtMTVkODAwODEzMjg4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDE2MzMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMDAwYzU0YjUxYmE5NGEyMTA0OWNjMDBkOTdhZGEzMzYzMDUyZjA3NmYyM2JjZjk1NzcwOWQ5ZDllMzY0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F0ySKut07Gue_JjF4neHHhdskaC642zb8n5f6Zj7Iww)
> 
> win11 ACT.呆萌整合

你好，我发现序列化问题是因为我在某处提供的链接有误，正确的链接应是：
#### 正式版：
```
https://raw.githubusercontent.com/BlackCleaverLoli/MissFisher/main/MissFisher.xml
```
#### 快照：
```
https://raw.githubusercontent.com/BlackCleaverLoli/MissFisher/main/MissFisher%20Snapshot.xml
```
抱歉给你带来了困扰……

**Comment by lileii** [comment]
再次感谢，不过还是写readme里面比较好

**Comment by BlackCleaverLoli** [comment]
> 再次感谢，不过还是写readme里面比较好

抱歉，我没有系统化学习过编程，也没有使用 GitHub 的经验。能详细说一下是把什么写在 readme 里面吗？
