### ISSUE TITLE
2.0鱼王涅普特龙预设错误

### ISSUE THREAD

**Issue by scyyc8876** [BlackCleaverLoli/MissFisher#3]
鱼饵应为极地磷虾而不是磷虾

**Comment by BlackCleaverLoli** [comment]
### **你好，谢谢你的反馈！**

内置预设中鱼皇 _涅普特龙_ 的钓饵 _磷虾_ 现已被更正为 _极地磷虾_ 。新的内置预设已被推送到 [Preset.csv](https://github.com/BlackCleaverLoli/MissFisher/blob/main/Preset.csv) 。

### **你可以使用以下方法来把内置预设同步到最新版：**
- 主界面：
在空天姬主界面中点击 `同步` 按钮。（需要角色已登录）

- 命令：
在游戏内发送命令 `/e ktjsync` 。

- 触发器：
在触发器插件页面打开主分组下的 `更多` 分组 - `右键` 触发器 `同步内置预设` - 点击 `执行（强制/条件）` 。

**Comment by scyyc8876** [comment]
![0bc9042c065ff85892a725c2359c4199](https://github.com/user-attachments/assets/20a3fc20-4816-47ff-83d1-5006bf7e69c4)
![317ed4633ce8fc113651bed41d37e760](https://github.com/user-attachments/assets/748356c6-b616-48ad-9aa3-f76bee39204b)
预设的后半段似乎属于巨齿鲨或者巨型乌贼

**Comment by BlackCleaverLoli** [comment]
> ![0bc9042c065ff85892a725c2359c4199](https://private-user-images.githubusercontent.com/181674372/367627831-20a3fc20-4816-47ff-83d1-5006bf7e69c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NDEzMDgsIm5iZiI6MTcyNjQ0MTAwOCwicGF0aCI6Ii8xODE2NzQzNzIvMzY3NjI3ODMxLTIwYTNmYzIwLTQ4MTYtNDdmZi04M2QxLTUwMDZiZjdlNjljNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQyMjU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDBkNWIzMTUyMDFkYmNjZmFhNTJkN2EwYmIxOTgyNDYzMDA3NzVhOGNjNzQxNDA5OWYwZGYwMzk3ZGQ1MzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qT1p-jwsSdxbWNjr6osB6U9X69qO78jIfPeX9bSw2Bw) ![317ed4633ce8fc113651bed41d37e760](https://private-user-images.githubusercontent.com/181674372/367627844-748356c6-b616-48ad-9aa3-f76bee39204b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NDEzMDgsIm5iZiI6MTcyNjQ0MTAwOCwicGF0aCI6Ii8xODE2NzQzNzIvMzY3NjI3ODQ0LTc0ODM1NmM2LWI2MTYtNDhhZC05YWEzLWY3NmJlZTM5MjA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQyMjU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWE1MmY5MWY2NWFkOTNhODE0NDVlNGI4OWQyODFiODE4MDc3ZmEzZDk4NTFlMGU5MGZhNDQzZmI1MWI0OGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Keh-PZUcLgJAGV1N6jB7gtJi-Xfu7Sd6ExO35vuRas) 预设的后半段似乎属于巨齿鲨或者巨型乌贼

_涅普特龙_ 可以被不同的钓法钓到，在网站鱼糕上你可以通过把鼠标移动到上图的 `┇` 标志上来查看不同的钓法。

在内置预设中使用的是以小钓大的钓法，因以小钓大有更大的概率钓到 _涅普特龙_  。
