### ISSUE TITLE
请问能不能把计时插件分离出来

### ISSUE THREAD

**Issue by xRhapsodi** [BlackCleaverLoli/MissFisher#4]
很喜欢计时的ui，但是其他的部分用不到，想请问下能不能单独把计时、杆型、幻海的悬浮窗单独分离出来一个版本？

**Comment by BlackCleaverLoli** [comment]
指的是不需要自动、默语播报和 TTS 吗？

**Comment by xRhapsodi** [comment]
是的是的，tts的话就有个分辨不同杆型的提示音就挺好的了。不知道会不会太麻烦！

**Comment by BlackCleaverLoli** [comment]
**已剥离大部分功能为 `风筝猫 Gaelicat` 。**
此版本的功能：
- **悬浮窗：** 显示竿时竿型、显示幻海流时间，显示采集力自然回复所需的倒计时。
- **咬饵竿型播报：**  TTS 与内置音效（自订音效使用 base64 转码为临时文件播放）。
- **功能设置：** 通过手动执行触发器分组下的触发器来更改设置。

你可以销毁空天姬配置来帮我测试 `风筝猫 Gaelicat` ，销毁空天姬配置的方法如下：
在 Trn 界面 Ctrl+E - `字典变量` - `永久变量` - 选中名为 `空天姬配置` 的字典 - 点击 `销毁变量` - 点击 `是`

然后，导入 `Gaelicat.xml` 到 Trn 中，在游戏日志活动的情况下 `风筝猫 Gaelicat` 应该会自动初始化。你可以通过海钓来测试 `风筝猫 Gaelicat` 的功能，看看它显示的竿时、竿型和幻海流时间有没有错误。

下载 `Gaelicat.xml` ：[ [123 云盘](https://www.123684.com/s/YJHhTd-81H13) ] | [ [Gitee 镜像](https://gitee.com/bcloli/MissFisher/blob/main/Gaelicat.xml) ] | [ [GitHub](https://github.com/BlackCleaverLoli/MissFisher/blob/main/Gaelicat.xml) ]

**Comment by BlackCleaverLoli** [comment]
### 风筝猫 Gaelicat 已更新到 `v1.1` 。

- 现在提供把自定义音效文件放至指定目录，然后更改为指定的名称的方法来使用自定义音效报竿。

**下载：** [ [123 云盘](https://www.123684.com/s/YJHhTd-M4H13) ] | [ [Gitee](https://gitee.com/bcloli/MissFisher/blob/main/Gaelicat.xml) ] | [ [Github](https://github.com/BlackCleaverLoli/MissFisher/blob/main/Gaelicat.xml) ]

---
感谢你的测试！

> 添加幻海流悬浮窗位置修改   

不打算添加这个功能。此外，因为幻海流悬浮窗只会在海域切换时刷新位置，在中途使用命令调整位置可能不会立刻表现出来。


> 添加非采集状态是否显示GP回复倒计时开关

我并不打算为这个部分继续投入精力，因为其不是必须的。

**Comment by xRhapsodi** [comment]
全部功能都可以正常使用，辛苦了，谢谢！
