### ISSUE TITLE
DR修改了换饵指令

### ISSUE THREAD

**Issue by LumiNosityAl1ve** [BlackCleaverLoli/MissFisher#5]
测试时候一直显示/bait 指令不存在，请问这个测试指令影响海钓吗？

**Comment by LumiNosityAl1ve** [comment]
现在换饵指令是/pdr bait，还是只是测试这样

**Comment by BlackCleaverLoli** [comment]
你好，这个报错 `/bait 指令不存在` 不影响DR的换饵也不影响海钓。

因为往期版本一直支持STP的换饵指令，所以当没有开启STP的换饵指令功能时会有一个错误消息。STP现在仍不支持游动饵的更换，未来的空天姬将不再继续支持STP换饵，也就不再发送STP换饵指令。

**Comment by LumiNosityAl1ve** [comment]
辛苦！
