### ISSUE TITLE
今天打开呆萌act发现报错，空天姬打不开了

### ISSUE THREAD

**Issue by WSMTBG** [BlackCleaverLoli/MissFisher#6]
2024-11-08 12:22:55.623	错误	脚本代码运行时遇到错误：
System.TypeInitializationException: “PostNamazuExtension”的类型初始值设定项引发异常。 ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Submission#0.PostNamazuExtension..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Submission#0.PostNamazuExtension.Log(DebugLevelEnum level, String msg)
   在 Submission#0.<<Initialize>>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Triggernometry.Interpreter.<>c__DisplayClass14_1.<<Evaluate>b__2>d.MoveNext()
2024-11-08 12:22:55.623	错误	脚本代码运行时遇到错误：
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 System.String.get_Chars(Int32 index)
   在 Submission#0.<>c.<<Initialize>>b__0_0(String item)
   在 System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   在 Submission#0.<<Initialize>>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Triggernometry.Interpreter.<>c__DisplayClass14_1.<<Evaluate>b__2>d.MoveNext()
2024-11-08 12:22:55.623	错误	脚本代码运行时遇到错误：
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Submission#0.MissFisherExtension.ScanSignatures()
   在 Submission#0.MissFisherExtension.OnXivProcUpdate()
   在 Submission#0.MissFisherExtension.Init()
   在 Submission#0.<<Initialize>>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 Triggernometry.Interpreter.<>c__DisplayClass14_1.<<Evaluate>b__2>d.MoveNext()

**Comment by BlackCleaverLoli** [comment]
请尝试更新 trn 和鲶鱼精
https://github.com/BlackCleaverLoli/MissFisher?tab=readme-ov-file#act-%E5%8F%8A-act-%E6%8F%92%E4%BB%B6
或者检查插件优先级顺序

**Comment by WSMTBG** [comment]
> 请尝试更新 trn 和鲶鱼精 https://github.com/BlackCleaverLoli/MissFisher?tab=readme-ov-file#act-%E5%8F%8A-act-%E6%8F%92%E4%BB%B6 或者检查插件优先级顺序

顺序应该没问题，鲶鱼精和Triggernometry刚刚点过更新，也还是打不开
![ymhxorux lr0](https://github.com/user-attachments/assets/57203ada-0568-4f41-a371-9625f12f8fc4)
![7dbd96904d97ec0139a10537cf3aa339](https://github.com/user-attachments/assets/39894b19-b4c3-4fb5-8a3f-0804c85c75b4)

**Comment by BlackCleaverLoli** [comment]
了解了，正在排查

**Comment by BlackCleaverLoli** [comment]
已排查到问题，将在下一个版本修复。除了主界面，你还可以 [使用命令来使用空天姬功能](https://github.com/BlackCleaverLoli/MissFisher?tab=readme-ov-file#%E5%91%BD%E4%BB%A4) 。

**Comment by BlackCleaverLoli** [comment]
已排查到根源，因预设键为空，导致脚本在排除以数字开头的键时出现问题。

已推送删除空键名的预设文件，你可以手动在触发器分组下同步最新的预设，成功同步最新版本的内置预设后应该就可以打开主界面了。

**Comment by WSMTBG** [comment]
> 已排查到根源，因预设键为空，导致脚本在排除以数字开头的键时出现问题。
> 
> 已推送删除空键名的预设文件，你可以手动在触发器分组下同步最新的预设，成功同步最新版本的内置预设后应该就可以打开主界面了。

能打开了..但默语频道没消息是我的问题吗..

**Comment by BlackCleaverLoli** [comment]
> > 已排查到根源，因预设键为空，导致脚本在排除以数字开头的键时出现问题。
> > 已推送删除空键名的预设文件，你可以手动在触发器分组下同步最新的预设，成功同步最新版本的内置预设后应该就可以打开主界面了。
> 
> 能打开了..但默语频道没消息是我的问题吗..

你的鲶鱼精初始化提示很奇怪，我的鲶鱼精初始化之后的提示语是中文的，你可以尝试更新鲶鱼精

**Comment by WSMTBG** [comment]
> > > 已排查到根源，因预设键为空，导致脚本在排除以数字开头的键时出现问题。
> > > 已推送删除空键名的预设文件，你可以手动在触发器分组下同步最新的预设，成功同步最新版本的内置预设后应该就可以打开主界面了。
> > 
> > 
> > 能打开了..但默语频道没消息是我的问题吗..
> 
> 你的鲶鱼精初始化提示很奇怪，我的鲶鱼精初始化之后的提示语是中文的，你可以尝试更新鲶鱼精

也没错啊...
![hnyadngt hsv](https://github.com/user-attachments/assets/0847fc88-7605-4386-ac14-7915222ab611)

**Comment by BlackCleaverLoli** [comment]
我不是很清楚问题在哪了，你可以尝试重启游戏和act，或者查看鲶鱼精页面有没有报错

**Comment by WSMTBG** [comment]
> 我不是很清楚问题在哪了，你可以尝试重启游戏和act，或者查看鲶鱼精页面有没有报错

游戏act全部重启，正常了
